### ISSUE TITLE
Frecklecute command fails in local repository if command name == role name

### ISSUE THREAD

**Issue by lalmeras** [makkus/freckles#29]
* freckles version: 0.4.3
* Python version: 2.7.13
* Operating System: Fedora 26

### Description

I have a frecklecute repository with a command that have the same name than an embedded role.

If I run the frecklecute locally, it fails with a No such command.
If I run the frecklecute remotely, it succeeds.

### What I Did

```
frecklecute -r https://github.com/powo-roles/test.freckles.git rolename
# [...] -> success
cd /tmp
git clone https://github.com/powo-roles/test.freckles.git
cd test.freckles
frecklecute -r $PWD rolename
# [...]
# Error: No such command "rolename".
```

**Comment by makkus** [comment]
Hm, interesting, thanks!

if you use a relative or absolute path (but not current directory with either $PWD or ' . '):
```
$ git clone https://github.com/powo-roles/test.freckles.git
...
$ frecklecute -r test.freckles/ rolename
 -> success
```
Most be something in the conversion of the current directory to absolute path that works differently than when using any other path. I'll have a look.

**Comment by makkus** [comment]
Ok, I think I figured out what the problem is. 

It's not the command name that is the problem, but that there is a folder named 'rolename' in the current directory. 

The way `frecklecute` checks which command to execute works by first trying to find a file with the command name, which in this case exists, and it'a a folder. If you move the folder to a different location, it would have worked.

Either way, fixed in latest git by checking if there is an actual file, not a folder, named like the command.
