### ISSUE TITLE
Documentation's improvement

### ISSUE THREAD

**Issue by lalmeras** [makkus/freckles#5]
Hi,

Thanks for this piece of software that solves elegantly environment's initialization by plugging together all the tools I liked (python, ansible, ...)

I see your response on my PR that underlines that freckles is under heavy development and not ready for production-use, but I think it is already quite usable and usefull, and I'm willing to help and follow its development towards stable release.

Here are some gaps that may be addressed to improve the documentation. In the provided examples, it is explained that freckles `reads all the metadata it can find`, but the location and format of this metadata is not explained. After some browsing, I conclude the following rules:

  * .dotfiles.freckle are one of this metadata sources: but I am not sure if name must be .dotfiles.freckle, or can be *.freckle ?
  * at least one .dotfiles.freckle is needed to trigger freckles processing of the repository
  * only sibling directories of .dotfiles.freckle files are handled by freckle. A *simple* repository may contain a root .dotfiles.freckle. Your makkus/dotfiles repository, a bit more complex, provides .dotfiles.freckle inside first-level directories. Is there any other use case ?
  * there are some .package_freckle files that seem to provide additional configuration to launched ansible modules. The example I found is `stow_delete_conflicts: yes` in dotfiles/minimal/bash. From my understanding, their purpose is to provide specific (ansible) configuration locally (for the containing directory). prefix used for the property (stow for this example) targeted ansible module.
  * there is some sort of default behavior for each .dotfiles.freckle that is the following: for each sibling directory install a package of the same name (with default package manager by default, or the one configured by .dotfiles.freckle file), and stow each sibling directory in HOME folder. I think that a .dotfiles.freckle file equivalent to the default behavior applied on sibling directories may help to understand and customize the default behavior.
  * I am not sure about the format of a minimal .dotfiles.freckle; does an empty file is enough ? It seems this is the case, cf https://github.com/makkus/dotfiles/blob/master/misc/.dotfiles.freckle
  * configurations that apply to all the sibling directories are put directly under the `vars:` key in .dotfiles.freckle
  * configurations that apply to a single package are put under vars/packages/[package] (example here for zplug : https://github.com/makkus/dotfiles/blob/master/minimal/.dotfiles.freckle)
  * what is the purpose of .no_install.frkl ? Is it used to mark the containing directory to be stow, but not to use the directory name to install a package ? I see there are also .no_stow.frkl. I'm confused because these files are not in .dotfiles.freckle enabled directories.

Are you interested in any PR for documentation ? Are you interested in sharing about freckles' development (gitter, irc) ?

**Comment by makkus** [comment]
Hi again. 

Good questions :-) First of all, yup, sure interested in contributions and also happy to open up channels to enable collaboration and all that. As I said, I'm not really ready with my design yet, so I might not be as responsive to bug reports/feature requests as I might be later, once its released. Got a pretty good idea what I want the first release of freckles to look like (even though I'm still fuzzy on the details -- see below).
Will open up a gitter in a minute, feel free to join there and we can have a chat to clear up any other questions.

As for the metadata format: mostly your guesses were right, although I am still uncertain about how to best layout those metadata/marker files, esp. in the interest of making freckles as generic as possible, to handle all kind of scenarios later on.

I did some more thinking over the last few days, and I think I know how I'll implement this now. I tried a few different approaches in the past, and I wasn't totally happy with any of them. I'll sketch some outlines below, in case you are interested, and you might have some feedback.

I'll do a proper write-up about the special, 'elastic' yaml format I'm using later on, as it's an important piece of the puzzle and the documentation on the 'frkl' readme is not really sufficient. But I implemented that a few months ago, and it looks like I was a bit more lucid at that time than I've been since, so, ever since then I'm trying to figure out myself why it works, and how :-)

Right, so. One of my main objectives for the configuration is that, for the most common tasks, the least amount of configuration should be necessary. While still retaining options do do more fine-grained configuration if the requirements arise, or once the user becomes more comfortable with freckles. Those more advanced options should be totally optional though. I was using my own dotfiles directory as an example for the more advanced use-case, as I use subfolders to be able to mix and match 'scenarios' (x-applications, non-x applications, minmal shell setup, etc.), git-crypt to encrypt a few semi-sensible files, and also nix and conda as package managers in addition to the system one. All the metadata files you found in my dotfiles repo are basically necessary to enable the fine-grained control I need. But all of them should be optional for simple cases.

So, keeping all that in mind: basically freckles works on folders with some sort of structure, and code or  data in them. I started to call such a folder a 'freckle', not sure if that's just silly though :-)

Usually one freckle will be of one type (e.g. containing dotfiles, or being a python project, or java, or an ansible role, maybe even a doctoral thesis, whatever...). With freckles, you apply a profile (haven't been able to come up with a better name yet) to a freckle. The profile contains the list of instructions to execute, and the variables that are available to tweak that behaviour (more or less 'ansible roles for data' instead of for infrastructure, if that makes any sense). And although I can't really think of a good example, intuitively I want one freckle to be able to have multiple profiles, if necessary.

To make it clear to freckles that it deals with such a folder, it can contain a marker file that ends with '.freckle'. In the iteration you were looking at let every such marker file also contain a profile name in the filename (thus, '.dotfiles.freckle -- indicating this freckle contains data of type dotfiles). I did that so a) one can see straight away which profile(s) is/are supported, with only having to look at the folder/filename structure, and b) to easily enable a 'freckle' to have multiple profiles, with overlapping metadata variables. 

After my recent thinking I decided that is overkill and over-engineering though, and this is what I'll change:

Every freckle will have a '.freckle' file in its root. If freckles is pointed to a folder with no .freckle file, it will assume the root of the folder is the freckle.
The .freckle file can be empty, in which case the profile that freckles will use with it must be determined by the user when running the freckles cli (in the future I could even imagine some sort of auto-detect, but that's probably really not necessary). The .freckle file can also contain metadata in (elastic) yaml format. This metadata can contain the list of profiles a freckle supports (and a 'default' one in case it has multiple), and the variables to tweak the profile execution. On the client side, a 2nd .freckle metadata dictionary can be provided, to overlay the whole or parts of the .freckle file. But in most cases this should not be necessary at all, I really want the freckle to contain all the information that is needed to describe it and do useful stuff with it.

As an example: for the 'dotfiles' profile, relevant metadata would be packages to install on a system where this set of dotfiles is used, which package manager to use for each of those packages (system, conda, nix, pip, npm, maven, whatnot), the package name of each of those packages on different platforms (optional, as most of the time the name will be the same). Whether to 'stow' this set of dotfiles or not. Whether to overwrite existing dotfiles that conflict with ones contained in this freckle. 

Currently the 'dotfiles' profile enables the user to specify a list of packages to install under the 'packages' key in the metadata. In addition, it'll list (non-recursively) all child folders, and assume the name of the folder is the name of a package to install. I'm still undecided as to whether to enable that behaviour by default or not, input appreciated. If it is the default, then that would make it easier to not require  to have a .freckle marker file at all for most dotfile repos: freckles would just checkout the whole repo, install app packages that correspond to the child-folder names, then symbolically links all the files in those subfolders. In most cases this will be good enough, as most people only work on one OS, and even if they work with more than one regularly, chances are that package names of end-user applications are the same across system package managers (emacs, zsh, cowsay, you get the idea...). 
And should that change, and a users dotfiles get more complicated, that can be accommodated by just augmenting the dotfiles freckle with metadata, as necessary.

Now, one of the more advanced things are the (current) .package_freckle metadata files. I found those to be helpful to be able to control freckles behavior on a per-folder basis without the main '.freckle' metadata file becoming too complex. I'll keep those, I think, but make some slight changes in how they are parsed to make them more generic and usable for every profile (not just 'dotfiles', as it is the case now). I don't imagine them to be widely used, but I'll want to use them, which is good enough a reason for me :-)

Does any of this make any sense? Happy to answer questions or get some feedback. I'll do the relevant documentation once the metadata format is fixed in place. Shouldn't be too much work, only have to move a few pieces of code to other places.

I also don't have a satisfactory solution on how to cleanly separate those profiles out on the freckles/ansible end. Ideally I'd like to use one ansible role for each of the profiles, but for a few technical reasons that doesn't seem to be possible. This is one of the problems that can last until after the first release though, since it won't change the user interface.

There is quite a bit more that needs to be documented. The rough plan was to get onto that in the next 2 weeks, wanted to have a first release early September, so if all goes as usual, look out for that sometime in October...

Thanks for asking those questions! I think I can use my response here as a first draft for my 'profiles' documentation :-)

**Comment by lalmeras** [comment]
Thanks for all these insights. I think the best thing I can do for the moment is to follow your changes on the project and to try to port my own installation scripts to freckle as it may provide both an example and a use case for testing.

Thanks for the explanation about profiles ; I think it will be a big help to understand freckles' code and start using it.

And this big picture makes sense for me.

**Comment by makkus** [comment]
All right, closing this, as freckles has changed quite a bit since the initial ticket was opened and most of the questions are not relevant anymore. Also, there is now a decent amount of documentation (with bits missing here and there).

Happy to get new tickets about specific issues related to documentation though.
